repo_name: MEV-Protocol/platform-docs
repo_url: https://github.com/MEV-Protocol/platform-docs
site_author: MEV.io
site_description: MEV Auction documentation for builders, searchers and liquid staking protocols.
site_name: MEV Auction
site_url: https://mevauction.com
copyright: Manifold Finance, Inc and its contributors. Creative Commons Attribution-NonCommercial-NoDerivs 2.5
use_directory_urls: true

theme:
  name: material
  custom_dir: .docs/overrides/
  features:
    - toc.follow
    - toc.integrate
    - content.footnote.tooltips
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetchn
    #    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
  palette:
    - scheme: "default"
      primary: "ethereum-blue"
      accent: "deep orange"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: "slate"
      primary: "ethereum-blue"
      accent: "red"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
  google:
    site_verification:
      - ''
    tag_manager: ''
  version:
    provider: mike
    default: latest-release

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - exclude:
      glob:
        - README.md
        - "*.gotmpl"
        - "*.gotmpl.md"
  - awesome-pages
  - macros:
      module_name: .docs/macros/includes/main
  - mike:
      version_selector: true # set to false to leave out the version selector
      css_dir: css # the directory to put the version selector's CSS
      javascript_dir: js # the directory to put the version selector's JS
      canonical_version: null
        # uses the version specified via `mike deploy`
markdown_extensions:
  - mdx_math
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: ./index.md
  - Developers:
      - Getting Started: Developers/index.md
      # - Auctioneer: Developers/auctioneer.md
      - Interface: Developers/interface.md
      - Builders & Searchers: Developers/builders.md
      - Testnet: Developers/testnet.md
      - Payment Methods: Developers/payment-methods.md
      - SDK: Developers/sdk.md
  - Learning:
      - Flashbots Comparison: Learning/flashbots-comparison.md
      - Auction Design: Learning/aup_auction.md
      - Forward Contracts: Learning/Forward-Contracts.md
  # Disable Article
  #      - 'Secondary Market': 'Learning/secondary-market.md'
  - Clients:
      - Overview: Clients/index.md
      - Clients: Clients/clients.md
      - Validators: Clients/validators.md
      - Configuration: Clients/configuration.md
      - Accounting: Clients/accounting.md
      - Relay: Clients/relay.md
  - Relay:
      - SecureRpc Relay: Relay/index.md
      - Captive Insurance: Relay/captive-insurance.md
      - SecureRPC Relay: https://securerpc.com
  - API:
      - Overview: api/index.md
      - Relay: api/relay.md
      - Validator Self Report: api/self-report.md
      - Beta Auction: api/beta-auction.md
      - Bundle: api/bundle.md
      - Signature Scheme: api/signature-scheme.md
  - Reference:
      - Contract Design: Reference/contract_design.md
      - Contract Summary: Reference/contract_summary.md
      - Glossary: Reference/glossary.md
      - RPC Payload: Reference/rpc-payload.md
      - Constant Values: Reference/constants.md
      - ERC 6909: Reference/erc6909.md
  - Legal:
      - Overview: Legal/index.md
      - Compliance: Legal/CDD.md
      - Content Disclaimer: Legal/Content-Disclaimer.md
      - Disclosure Statement: Legal/Disclosure-Statement.md
  - Rulebook:
      - Bylaws: guidelines/bylaws.md
      - Definitions: guidelines/definitions.md
      - Settlement: guidelines/delivery-and-settlement.md
      - General: guidelines/general.md
      - Governance: guidelines/governance.md
      - Clearing: guidelines/network-clearing-participants.md
      - Obligations: guidelines/obligations.md
      - Suspension: guidelines/suspension.md
